name: PerfectTimeTo - Build, Test, and Deploy
run-name: ${{ github.actor }}

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false
  
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'

    - run: echo "Repo ${{ github.repository }} has been cloned to the runner."

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Build
      run: yarn build

    - name: Pre-deploy
      run: yarn predeploy

    - name: Run tests
      run: yarn test

    - name: Configure Git identity
      run: |
        git config user.email ${{ vars.USER_EMAIL }}
        git config user.name ${{ vars.USER_NAME }}

    - name: Deploy to GitHub Pages
      run: yarn deploy-gh-pages
      env:
        deploy_key: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
        
    - name: Deploy to www.perfecttimeto.com
      run: yarn deploy-www
      env:
        deploy_key: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
